# debug/info
logLevel: debug
# BTC blockstream api
# https://github.com/Blockstream/esplora/blob/master/API.md
btcApiEndpoint: https://btc-rpc-testnet.lorenzo-protocol.xyz/testnet/api

tx-relayer:
  confirmationDepth: 6
  # BTC network type:mainet/testnet/signet
  netParams: testnet

database:
  host:
  port: 3306
  username: admin
  password: admin
  dbname: lorenzo

lorenzo:
  # cosmos Keyring
  # The keyring holds the private/public keypairs used to interact with a node
  # more detail: https://docs.cosmos.network/v0.45/run-node/keyring.html
  key: submitter
  key-directory: ./.testnet/node0/lorenzod
  # Select keyring's backend (os|file|test)
  keyring-backend: test
  # lorenzo genesis file chain-id
  chain-id: lorenzod_83291-1
  # lorenzo rpc
  rpc-addr: http://rpc-cosmos-testnet.lorenzo-protocol.xyz:26657
  # lorenzo cosmos account address prefix
  account-prefix: lrz
  gas-adjustment: 1.5
  gas-prices: 0alrz
  debug: true
  timeout: 20s
  output-format: json
  sign-mode: direct