logLevel: debug
dbDir: ./.testnet/db
btcApiEndpoint: http://45.76.152.81:8084/signet/api

tx-relayer:
  confirmationDepth: 6
  netParams: signet
  targetDepositAddress: tb1qrgg5gtf39jdyn2uvas6zaq0z4z8elz6encl2s2

lorenzo:
  key: submitter
  chain-id: lorenzod_83291-1
  rpc-addr: http://127.0.0.1:26657
  account-prefix: lrz
  keyring-backend: test
  gas-adjustment: 1.5
  gas-prices: 0alrz
  key-directory: ./.testnet/node0/lorenzod
  debug: true
  timeout: 20s
  output-format: json
  sign-mode: direct